---
- name: create docker image
  docker_image:
    name: farouklr01/cilab
    build:
      path: /var/lib/jenkins/workspace/ffffff
      pull: no 
    source: build
    state: present
    force_source: true
-  name: run container docker
   docker_container:
     name: Myapp_container
     image: farouklr01/cilab:latest
     state: started
     recreate: true
     ports:
      - "4200:80"
